# Generated by Django 5.1.4 on 2024-12-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TenderTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("procurement_type", models.CharField(max_length=10)),
                ("last_sequence", models.IntegerField(default=0)),
            ],
        ),
    ]
