# Generated by Django 5.1.4 on 2025-01-24 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ISOTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("last_sequence", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TenderTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(unique=True)),
                ("last_sequence", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="SystemActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField(default="No description provided")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Tender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tender_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "procurement_type",
                    models.CharField(
                        choices=[
                            ("Goods", "Goods"),
                            ("Works", "Works"),
                            ("Services", "Services"),
                            ("Consultancy", "Consultancy"),
                        ],
                        default="Goods",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("amendment", models.CharField(blank=True, max_length=10, null=True)),
                ("call_off", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "category_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("file_name", models.CharField(blank=True, max_length=200, null=True)),
                ("file_no", models.CharField(blank=True, max_length=100, null=True)),
                ("po_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "name_of_vendor_consultant",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "vendor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "vendor_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("invitation_date", models.DateField(blank=True, null=True)),
                ("closing_date", models.DateField(blank=True, null=True)),
                ("evaluation_date", models.DateField(blank=True, null=True)),
                ("date_of_contract", models.DateField(blank=True, null=True)),
                ("date_of_po", models.DateField(blank=True, null=True)),
                ("date_of_payment_memo", models.DateField(blank=True, null=True)),
                (
                    "sra_certification_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_sra_certification", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenders",
                        to="tender_app.category",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenders",
                        to="tender_app.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tenders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tender",
                "verbose_name_plural": "Tenders",
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_tender", "Can approve tender"),
                    ("can_reject_tender", "Can reject tender"),
                    ("can_view_all_tenders", "Can view all tenders"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ISODetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_number", models.CharField(max_length=255, unique=True)),
                ("division_name", models.CharField(max_length=255)),
                ("department_name", models.CharField(max_length=255)),
                ("procurement_type", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("sequential_number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tender_app.tender",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("officer", "Procurement Officer"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("is_account_active", models.BooleanField(default=False)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="tender_app.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["full_name"],
            },
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(
                fields=["-created_at"], name="tender_app__created_a61dda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(fields=["status"], name="tender_app__status_6eb27d_idx"),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(
                fields=["tender_number"], name="tender_app__tender__e72b11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tender",
            index=models.Index(
                fields=["department"], name="tender_app__departm_932ef2_idx"
            ),
        ),
    ]
