# Generated by Django 5.1.4 on 2024-12-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
