# Generated by Django 5.1.4 on 2024-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender_app", "0002_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tendertracker",
            name="procurement_type",
        ),
        migrations.AlterField(
            model_name="tendertracker",
            name="year",
            field=models.IntegerField(unique=True),
        ),
    ]
