# Generated by Django 5.1.4 on 2025-05-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0002_tender_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='vendor',
        ),
    ]
