# Generated by Django 5.1.4 on 2024-12-18 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender_app", "0004_department_name_tender"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tender_app.department",
            ),
        ),
    ]
