# Generated by Django 5.1.4 on 2024-12-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender_app", "0006_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
