# Generated by Django 5.1.4 on 2025-03-26 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0007_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tender',
            name='category',
            field=models.CharField(choices=[('Goods', 'Goods'), ('Technical Service', 'Technical Service'), ('Consultancy', 'Consultancy'), ('Works', 'Works')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='currency',
            field=models.CharField(choices=[('GHS', 'GHS'), ('USD', 'USD'), ('EUR', 'EUR')], default='GHS', max_length=3),
        ),
        migrations.AddField(
            model_name='tender',
            name='evaluation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tender',
            name='file_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tender',
            name='invitation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='payment_memo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tender',
            name='requests_aggregated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tender',
            name='sra_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tender',
            name='sra_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
        migrations.AddField(
            model_name='tender',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tender',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender_app.department'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='tender_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
