# Generated by Django 5.1.4 on 2024-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender_app", "0008_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Approved", "Approved")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
