# Generated by Django 5.1.4 on 2024-12-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tender_app", "0009_tender_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="amendment",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="call_off",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
