# Generated by Django 5.1.4 on 2025-03-26 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0011_breakfastitem_order_orderitem_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image (JPG, PNG or WebP, max 5MB)', null=True, upload_to='breakfast_items/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
