# Generated by Django 5.1.4 on 2025-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0013_division_isotracker_isonumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isonumber',
            name='division',
        ),
        migrations.AlterField(
            model_name='isonumber',
            name='letter_type',
            field=models.CharField(choices=[('RFQ', 'RFQ Letter'), ('PPA', 'Letter to PPA'), ('CTR', 'Letter to CTRC')], max_length=3),
        ),
    ]
