# Generated by Django 5.1.4 on 2025-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0015_isonumber_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
