# Generated by Django 5.1.4 on 2025-05-20 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0017_vendor_tenderitem_frameworkagreement_vendorbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworkagreement',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_agreements', to='tender_app.vendor'),
        ),
    ]
