# Generated by Django 5.1.4 on 2025-05-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0018_alter_frameworkagreement_vendor'),
        ('tender_app', '0018_tenderitem_appearance_tenderitem_assay_percentage_and_more'),
    ]

    operations = [
    ]
