# Generated by Django 5.1.4 on 2025-05-21 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0019_merge_20250521_1355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=10)),
                ('chemical_name', models.CharField(max_length=255)),
                ('formula', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(choices=[('HPLC', 'High Performance Liquid Chromatography Grade'), ('AR', 'Analytical Reagent Grade'), ('GC', 'Gas Chromatography Grade'), ('USP', 'United States Pharmacopeia Grade'), ('ACS', 'American Chemical Society Grade'), ('TECH', 'Technical Grade'), ('GEN', 'General Purpose Reagent Grade')], max_length=10)),
                ('package_size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tender_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemicals', to='tender_app.tenderitem')),
            ],
            options={
                'ordering': ['chemical_name', 'lot_number'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tender_app.tender')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tender_app.vendor')),
            ],
            options={
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tender_app.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChemicalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_type', models.CharField(choices=[('MOLAR_MASS', 'Molar Mass'), ('DENSITY', 'Density'), ('ASSAY', 'Assay'), ('PURITY', 'Purity'), ('APPEARANCE', 'Appearance'), ('VAPOR_DENSITY', 'Vapor Density'), ('IMPURITY', 'Impurity Limit'), ('PH', 'pH'), ('BOILING_POINT', 'Boiling Point'), ('FLASH_POINT', 'Flash Point'), ('SOLUBILITY', 'Solubility'), ('OTHER', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='tender_app.chemical')),
            ],
            options={
                'ordering': ['chemical', 'spec_type'],
                'unique_together': {('chemical', 'spec_type')},
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#007bff', help_text='Hex color code', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Task Categories',
                'unique_together': {('name', 'user')},
            },
        ),
    ]
